#!/bin/sh

YEAR="1997"
USERNAME=ngseke

mkdir $YEAR
cd $YEAR
git init
for i in {0..364}
do
  timestamp=`expr 852105600 + 86400 \* $i`
  date=`date -r $timestamp -u +%FT%TZ`
  echo "**$date** - Generated by https://github.com/antfu/1990-script" > README.md
  git add .
  GIT_AUTHOR_DATE="$date" GIT_COMMITTER_DATE="$date" git commit -m "$YEAR"
done

git remote add origin https://github.com/$USERNAME/$YEAR.git
git push -u origin master -f
cd ..
rm -rf $YEAR

# echo
# echo Cool, check your profile now: https://github.com/$USERNAME
